language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install gcc libffi-dev libldap2-dev libsasl2-dev libssl-dev python-dev
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: opennode
  password:
    secure: X3heaXkI94PPSqZD2VmMRQZoJtlf6TFQGeSrRXB3IFmMBt/4nenVxvp7Sub6AcqJXTwAjN93UvJ2bL5VCH0PXq6RvUPj5P9MPkPPBJG83VO15sua+kDyMpecRyYqk2EHWFS1uk0+WppTSI8gR/yWyppzDuwvR6BEsC9TtVfE6OKrgPHx838Ejd2Md5XotV6K7JWsmvnn/GgR8ANeOQg+rIpQxuGSsFgthS9t6kIBD/YBgRFnTOl7dDFTcZ0wVvDmkPAahkyr9faDi2jGe5SlpMcQZdNvYmP5mOVgOEG7HcJ0yPPtgvLhgB3uG9ihosH/yh0hddvu0B3K1J6OzmA7/9sgmVSwDB6v5DwB1C/hq7wemXkhLHwrxuNWBq6dUfHwaCR+RH6FFDF4hQEMK6x6V0I1DIeaKD3vW9wK1ZsZLS1D4vZ5XYuRwYAVHvgCEhX+jLyOeLvVYnOQ5Ar6tCOqB0vQfF+tsQTruMG+SYKD0d+8kp/DcEyOLGV8RyguGNlSxn4hOfSi4giAgePYXqB8eyCJ046ju0PZl0Df6ZBW5tKSpQR3P0/pK1DLxRybaOYsu3DAyEG25P1fja/6xDlBkvlJu3RH+RLToh6v9/3A+NRmNb3GftrzM5lmXPtmKOmLBEtPtF/Nt+moNChyoRIXtRlVLp6Tlwj9sRh8f0ANmUc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: opennode/nodeconductor-auth-social
